let students= [
    {
        Name:"Aman",
        College:"IEMK",
        Stream:"ECE",
        Age:21
    },
    {
        Name:"Shradha",
        College:"NSIT",
        Stream:"CSE",
        Age:23
    },
    {
        Name:"Affan",
        College:"Narula",
        Stream:"CSE",
        Age:20
    }
]